### ISSUE TITLE
Failed to load plugin: CpuidSpoofer.dp64

### ISSUE THREAD

**Issue by amethyst8118** [jonatan1024/CpuidSpoofer#3]
![Screenshot_20210725_211329](https://user-images.githubusercontent.com/74958480/126904988-d439adb1-01a2-44d6-ae5b-d5e1e44fa531.png)
Tried it on the latest version as well, fails to load.

**Comment by jonatan1024** [comment]
Hello, please try the new version where VC++ runtime is no longer required:

https://github.com/jonatan1024/CpuidSpoofer/releases/download/v1.0.1/CpuidSpoofer.dp64

**Comment by jonatan1024** [comment]
Closing after a year of inactivity
