### ISSUE TITLE
Failed to load plugin: CpuidSpoofer.dp32

### ISSUE THREAD

**Issue by lehrerhans** [jonatan1024/CpuidSpoofer#4]
Hallo,
the x32-Version is not visible in the Plugin-Menue.
the x64-Version is visible.

x64dbg latest version.
snapshot_2023-01-25_11-53

maybe you know the reason
regards 
chris

**Comment by jonatan1024** [comment]
Hello, please try the new version where VC++ runtime is no longer required:

https://github.com/jonatan1024/CpuidSpoofer/releases/download/v1.0.1/CpuidSpoofer.dp32

**Comment by lehrerhans** [comment]
Works. Thank you very much!
